In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("/mnt/c/Users/manav/OneDrive/Desktop/paitent health/Patient_Health_Records_Raw.csv")

In [6]:
df.head(10)

,Patient_ID,Name,Age,Gender,City,BMI,Blood_Pressure,Heart_Rate,Cholesterol_Level,Diabetic,Smoker,Medications,Last_Visit_Date,Follow_Up,Diagnosis_Code,Notes,Has_Disease
0,ID-00001,"SMITH, ALICE",250,Unknown,Boston,22kg/m2,120 over 80,83,190,Unknown,yes,NaN,Apr 15 2021,30,A00,Patient feeling fine 🙂,0
1,ID-00002,"SMITH, ALICE",-5,FEMALE,newyork,25.8,NaN,500,normal,N,No,NaN,2021-07-10,NaN,unknown,"BP high, needs recheck",unknown
2,ID-00003,John Doe,-5,NaN,Nwe Yrok,22kg/m2,120 - 80,500,190,no,Former,"aspirin,metformin",Apr 06 2021,30,B20,NaN,unknown
3,ID-00004,michael brown,80,F,New York,33.4,NaN,eighty,250,y,EX-smoker,NaN,20241113,30,NaN,Follow up soon,unknown
4,ID-00005,Jane Doe,250,male,la,30.1,120 over 80,0,normal,no,No,NaN,2025-09-27,NaN,I10,Patient feeling fine 🙂,1
5,ID-00006,michael brown,-5,Unknown,NaN,22kg/m2,120 - 80,63,normal,no,EX-smoker,NaN,2025-05-22,30,E11.9,NaN,0
6,ID-00007,"LEE, Sara",98,M,Chicago,NaN,120 over 80,108,normal,Unknown,No,"aspirin,metformin",09/03/2024,NaN,E11.9,Follow up soon,unknown
7,ID-00008,"SMITH, ALICE",250,M,New York,22.5,120 over 80,85,250,y,NaN,NaN,May 22 2022,NaN,I10,"BP high, needs recheck",unknown
8,ID-00009,John Doe,250,NaN,Boston,NaN,120 over 80,500,high,N,Former,Aspirin; Metformin,02/03/2020,30,unknown,NaN,0
9,ID-00010,michael brown,-5,Unknown,Chicago,21.5,NaN,eighty,NaN,no,Former,NaN,2025-03-30,30,A00,"BP high, needs recheck",1

In [7]:
df.tail()

,Patient_ID,Name,Age,Gender,City,BMI,Blood_Pressure,Heart_Rate,Cholesterol_Level,Diabetic,Smoker,Medications,Last_Visit_Date,Follow_Up,Diagnosis_Code,Notes,Has_Disease
9995,ID-09996,"SMITH, ALICE",250,F,la,22kg/m2,120 - 80,eighty,NaN,N,EX-smoker,Aspirin; Metformin,20210501,14,E11.9,Patient feeling fine 🙂,0
9996,ID-09997,John Doe,12,FEMALE,la,22kg/m2,120 over 80,0,190,y,Former,"aspirin,metformin",Feb 21 2020,NaN,I10,Follow up soon,unknown
9997,ID-09998,michael brown,-5,NaN,Nwe Yrok,NaN,120/80,71,190,Unknown,EX-smoker,Lisinopril / Metformin,20250215,two weeks,B20,NaN,0
9998,ID-09999,John Doe,250,Unknown,Chicago,22.4,112/98,0,high,y,EX-smoker,NaN,2022-03-19,14,B20,"BP high, needs recheck",0
9999,ID-10000,John Doe,250,Unknown,Chicago,NaN,NaN,500,NaN,Yes,Former,NaN,Jan 06 2025,two weeks,E11.9,Patient feeling fine 🙂,unknown

In [9]:
df.shape

(10000, 17)

In [10]:
df.info

<bound method DataFrame.info of      Patient_ID            Name  Age   Gender      City      BMI  \
0      ID-00001    SMITH, ALICE  250  Unknown    Boston  22kg/m2
1      ID-00002    SMITH, ALICE   -5   FEMALE   newyork     25.8
2      ID-00003        John Doe   -5      NaN  Nwe Yrok  22kg/m2
3      ID-00004   michael brown   80        F  New York     33.4
4      ID-00005       Jane  Doe  250     male        la     30.1
...         ...             ...  ...      ...       ...      ...
9995   ID-09996    SMITH, ALICE  250        F        la  22kg/m2
9996   ID-09997        John Doe   12   FEMALE        la  22kg/m2
9997   ID-09998   michael brown   -5      NaN  Nwe Yrok      NaN
9998   ID-09999        John Doe  250  Unknown   Chicago     22.4
9999   ID-10000        John Doe  250  Unknown   Chicago      NaN

     Blood_Pressure Heart_Rate Cholesterol_Level Diabetic     Smoker  \
0       120 over 80         83               190  Unknown        yes
1               NaN        500            normal        N         No
2          120 - 80        500               190       no     Former
3               NaN     eighty               250        y  EX-smoker
4       120 over 80          0            normal       no         No
...             ...        ...               ...      ...        ...
9995       120 - 80     eighty               NaN        N  EX-smoker
9996    120 over 80          0               190        y     Former
9997         120/80         71               190  Unknown  EX-smoker
9998         112/98          0              high        y  EX-smoker
9999            NaN        500               NaN      Yes     Former

                 Medications Last_Visit_Date  Follow_Up Diagnosis_Code  \
0                        NaN     Apr 15 2021         30            A00
1                        NaN      2021-07-10        NaN        unknown
2          aspirin,metformin     Apr 06 2021         30            B20
3                        NaN        20241113         30            NaN
4                        NaN      2025-09-27        NaN            I10
...                      ...             ...        ...            ...
9995      Aspirin; Metformin        20210501         14          E11.9
9996       aspirin,metformin     Feb 21 2020        NaN            I10
9997  Lisinopril / Metformin        20250215  two weeks            B20
9998                     NaN      2022-03-19         14            B20
9999                     NaN     Jan 06 2025  two weeks          E11.9

                       Notes Has_Disease
0     Patient feeling fine 🙂           0
1     BP high, needs recheck     unknown
2                        NaN     unknown
3             Follow up soon     unknown
4     Patient feeling fine 🙂           1
...                      ...         ...
9995  Patient feeling fine 🙂           0
9996          Follow up soon     unknown
9997                     NaN           0
9998  BP high, needs recheck           0
9999  Patient feeling fine 🙂     unknown

[10000 rows x 17 columns]>

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         9493 non-null   str
 1   Name               10000 non-null  str
 2   Age                10000 non-null  str
 3   Gender             8293 non-null   str
 4   City               8997 non-null   str
 5   BMI                7582 non-null   str
 6   Blood_Pressure     7970 non-null   str
 7   Heart_Rate         10000 non-null  str
 8   Cholesterol_Level  7948 non-null   str
 9   Diabetic           8359 non-null   str
 10  Smoker             6766 non-null   str
 11  Medications        5976 non-null   str
 12  Last_Visit_Date    10000 non-null  str
 13  Follow_Up          7476 non-null   str
 14  Diagnosis_Code     8325 non-null   str
 15  Notes              5976 non-null   str
 16  Has_Disease        7480 non-null   str
dtypes: str(17)
memory usage: 1.3 MB

In [12]:
df.drop("Notes", axis=1, inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         9493 non-null   str
 1   Name               10000 non-null  str
 2   Age                10000 non-null  str
 3   Gender             8293 non-null   str
 4   City               8997 non-null   str
 5   BMI                7582 non-null   str
 6   Blood_Pressure     7970 non-null   str
 7   Heart_Rate         10000 non-null  str
 8   Cholesterol_Level  7948 non-null   str
 9   Diabetic           8359 non-null   str
 10  Smoker             6766 non-null   str
 11  Medications        5976 non-null   str
 12  Last_Visit_Date    10000 non-null  str
 13  Follow_Up          7476 non-null   str
 14  Diagnosis_Code     8325 non-null   str
 15  Has_Disease        7480 non-null   str
dtypes: str(16)
memory usage: 1.2 MB

In [14]:
df.isnull().sum()

Patient_ID            507
Name                    0
Age                     0
Gender               1707
City                 1003
BMI                  2418
Blood_Pressure       2030
Heart_Rate              0
Cholesterol_Level    2052
Diabetic             1641
Smoker               3234
Medications          4024
Last_Visit_Date         0
Follow_Up            2524
Diagnosis_Code       1675
Has_Disease          2520
dtype: int64

In [15]:
df.nunique()

Patient_ID           9493
Name                    5
Age                   104
Gender                  5
City                    9
BMI                   202
Blood_Pressure       1431
Heart_Rate             74
Cholesterol_Level       4
Diabetic                5
Smoker                  4
Medications             3
Last_Visit_Date      5816
Follow_Up               3
Diagnosis_Code          5
Has_Disease             3
dtype: int64

In [16]:
df.drop("Patient_ID", axis=1, inplace=True)
df.drop("Name", axis=1, inplace=True)
df.drop("Last_Visit_Date", axis=1, inplace=True)

In [18]:
df.shape

(10000, 13)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                10000 non-null  str
 1   Gender             8293 non-null   str
 2   City               8997 non-null   str
 3   BMI                7582 non-null   str
 4   Blood_Pressure     7970 non-null   str
 5   Heart_Rate         10000 non-null  str
 6   Cholesterol_Level  7948 non-null   str
 7   Diabetic           8359 non-null   str
 8   Smoker             6766 non-null   str
 9   Medications        5976 non-null   str
 10  Follow_Up          7476 non-null   str
 11  Diagnosis_Code     8325 non-null   str
 12  Has_Disease        7480 non-null   str
dtypes: str(13)
memory usage: 1015.8 KB

In [20]:
print(df.columns.tolist())

['Age', 'Gender', 'City', 'BMI', 'Blood_Pressure', 'Heart_Rate', 'Cholesterol_Level', 'Diabetic', 'Smoker', 'Medications', 'Follow_Up', 'Diagnosis_Code', 'Has_Disease']

In [21]:
print(df.isnull().sum())

Age                     0
Gender               1707
City                 1003
BMI                  2418
Blood_Pressure       2030
Heart_Rate              0
Cholesterol_Level    2052
Diabetic             1641
Smoker               3234
Medications          4024
Follow_Up            2524
Diagnosis_Code       1675
Has_Disease          2520
dtype: int64

In [23]:
df.columns = df.columns.str.strip()

for col in df.select_dtypes(include="str"):
    df[col] = df[col].str.strip()

In [24]:
df['Blood_Pressure']

0       120 over 80
1               NaN
2          120 - 80
3               NaN
4       120 over 80
           ...
9995       120 - 80
9996    120 over 80
9997         120/80
9998         112/98
9999            NaN
Name: Blood_Pressure, Length: 10000, dtype: str

In [25]:
# Replace different separators with "/"
df['Blood_Pressure'] = (
    df['Blood_Pressure']
    .str.replace(' over ', '/', regex=False)
    .str.replace(' - ', '/', regex=False)
)

# Split into two columns
df[['Systolic_BP', 'Diastolic_BP']] = (
    df['Blood_Pressure'].str.split('/', expand=True)
)

# Convert to numbers
df['Systolic_BP'] = pd.to_numeric(df['Systolic_BP'], errors='coerce')
df['Diastolic_BP'] = pd.to_numeric(df['Diastolic_BP'], errors='coerce')

In [26]:
df['Blood_Pressure']

0       120/80
1          NaN
2       120/80
3          NaN
4       120/80
         ...
9995    120/80
9996    120/80
9997    120/80
9998    112/98
9999       NaN
Name: Blood_Pressure, Length: 10000, dtype: str

In [27]:
df[['Systolic_BP', 'Diastolic_BP']] = (
    df['Blood_Pressure'].str.split('/', expand=True)
)

In [28]:
df['Blood_Pressure']

0       120/80
1          NaN
2       120/80
3          NaN
4       120/80
         ...
9995    120/80
9996    120/80
9997    120/80
9998    112/98
9999       NaN
Name: Blood_Pressure, Length: 10000, dtype: str

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                10000 non-null  str
 1   Gender             8293 non-null   str
 2   City               8997 non-null   str
 3   BMI                7582 non-null   str
 4   Blood_Pressure     7970 non-null   str
 5   Heart_Rate         10000 non-null  str
 6   Cholesterol_Level  7948 non-null   str
 7   Diabetic           8359 non-null   str
 8   Smoker             6766 non-null   str
 9   Medications        5976 non-null   str
 10  Follow_Up          7476 non-null   str
 11  Diagnosis_Code     8325 non-null   str
 12  Has_Disease        7480 non-null   str
 13  Systolic_BP        7970 non-null   str
 14  Diastolic_BP       7970 non-null   str
dtypes: str(15)
memory usage: 1.1 MB

In [30]:
df['Systolic_BP'] = pd.to_numeric(df['Systolic_BP'], errors='coerce')
df['Diastolic_BP'] = pd.to_numeric(df['Diastolic_BP'], errors='coerce')

In [31]:
df[['Blood_Pressure', 'Systolic_BP', 'Diastolic_BP']].head(10)

  Blood_Pressure  Systolic_BP  Diastolic_BP
0         120/80        120.0          80.0
1            NaN          NaN           NaN
2         120/80        120.0          80.0
3            NaN          NaN           NaN
4         120/80        120.0          80.0
5         120/80        120.0          80.0
6         120/80        120.0          80.0
7         120/80        120.0          80.0
8         120/80        120.0          80.0
9            NaN          NaN           NaN

In [32]:
numeric_cols = [
    'Age',
    'BMI',
    'Heart_Rate',
    'Cholesterol_Level',
    'Systolic_BP',
    'Diastolic_BP'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    #convert into numerical

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                7511 non-null   float64
 1   Gender             8293 non-null   str
 2   City               8997 non-null   str
 3   BMI                5115 non-null   float64
 4   Blood_Pressure     7970 non-null   str
 5   Heart_Rate         7541 non-null   float64
 6   Cholesterol_Level  4018 non-null   float64
 7   Diabetic           8359 non-null   str
 8   Smoker             6766 non-null   str
 9   Medications        5976 non-null   str
 10  Follow_Up          7476 non-null   str
 11  Diagnosis_Code     8325 non-null   str
 12  Has_Disease        7480 non-null   str
 13  Systolic_BP        7970 non-null   float64
 14  Diastolic_BP       7970 non-null   float64
dtypes: float64(6), str(9)
memory usage: 1.1 MB

In [34]:
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                10000 non-null  float64
 1   Gender             8293 non-null   str
 2   City               8997 non-null   str
 3   BMI                10000 non-null  float64
 4   Blood_Pressure     7970 non-null   str
 5   Heart_Rate         10000 non-null  float64
 6   Cholesterol_Level  10000 non-null  float64
 7   Diabetic           8359 non-null   str
 8   Smoker             6766 non-null   str
 9   Medications        5976 non-null   str
 10  Follow_Up          7476 non-null   str
 11  Diagnosis_Code     8325 non-null   str
 12  Has_Disease        7480 non-null   str
 13  Systolic_BP        10000 non-null  float64
 14  Diastolic_BP       10000 non-null  float64
dtypes: float64(6), str(9)
memory usage: 1.1 MB

In [36]:
categorical_cols = [
    'Gender',
    'City',
    'Diabetic',
    'Smoker',
    'Medications',
    'Follow_Up',
    'Diagnosis_Code',
    'Has_Disease'
]

for col in categorical_cols:
    df[col] = df[col].fillna('Unknown')

In [37]:
print(df['Gender'].value_counts())

Gender
Unknown    3426
male       1703
FEMALE     1679
M          1607
F          1585
Name: count, dtype: int64

In [38]:
print(df['Smoker'].value_counts())
print(df['Diabetic'].value_counts())
print(df['City'].value_counts().head(20))

Smoker
Unknown      3234
EX-smoker    1739
Former       1718
No           1663
yes          1646
Name: count, dtype: int64
Diabetic
Unknown    3301
no         1721
Yes        1689
N          1651
y          1638
Name: count, dtype: int64
City
Chicago        1048
NY             1045
Boston         1023
la             1010
New York       1003
Unknown        1003
Nwe Yrok        992
newyork         974
chicago         971
Los Angeles     931
Name: count, dtype: int64

In [39]:
df['Gender'] = df['Gender'].replace({
    'male': 'Male',
    'M': 'Male',
    'FEMALE': 'Female',
    'F': 'Female'
})

In [40]:
df['Gender'].value_counts()

Gender
Unknown    3426
Male       3310
Female     3264
Name: count, dtype: int64

In [41]:
print(df['Smoker'].value_counts())
print(df['Diabetic'].value_counts())

Smoker
Unknown      3234
EX-smoker    1739
Former       1718
No           1663
yes          1646
Name: count, dtype: int64
Diabetic
Unknown    3301
no         1721
Yes        1689
N          1651
y          1638
Name: count, dtype: int64

In [42]:
df['Smoker'] = df['Smoker'].replace({
    'EX-smoker': 'Former',
    'Former': 'Former',
    'No': 'No',
    'yes': 'Yes'
})#clean smoker

In [43]:
df['Diabetic'] = df['Diabetic'].replace({
    'Y': 'yes',
    'N': 'No',
    'No': 'No',
    'yes': 'Yes'
})

In [44]:
print(df['Smoker'].value_counts())
print(df['Diabetic'].value_counts())

Smoker
Former     3457
Unknown    3234
No         1663
Yes        1646
Name: count, dtype: int64
Diabetic
Unknown    3301
no         1721
Yes        1689
No         1651
y          1638
Name: count, dtype: int64

In [45]:
df['Diabetic'] = df['Diabetic'].replace({
    'no': 'No',
    'y': 'Yes'
})

In [46]:
print(df['Smoker'].value_counts())
print(df['Diabetic'].value_counts())

Smoker
Former     3457
Unknown    3234
No         1663
Yes        1646
Name: count, dtype: int64
Diabetic
No         3372
Yes        3327
Unknown    3301
Name: count, dtype: int64

In [47]:
for col in ['City', 'Medications', 'Follow_Up', 'Diagnosis_Code', 'Has_Disease']:
    print("\n", col)
    print(df[col].value_counts().head(20))

 City
City
Chicago        1048
NY             1045
Boston         1023
la             1010
New York       1003
Unknown        1003
Nwe Yrok        992
newyork         974
chicago         971
Los Angeles     931
Name: count, dtype: int64

 Medications
Medications
Unknown                   4024
aspirin,metformin         2011
Lisinopril / Metformin    2011
Aspirin; Metformin        1954
Name: count, dtype: int64

 Follow_Up
Follow_Up
two weeks    2540
Unknown      2524
30           2474
14           2462
Name: count, dtype: int64

 Diagnosis_Code
Diagnosis_Code
B20        1700
unknown    1691
Unknown    1675
I10        1664
E11.9      1663
A00        1607
Name: count, dtype: int64

 Has_Disease
Has_Disease
Unknown    2520
0          2513
unknown    2506
1          2461
Name: count, dtype: int64

In [48]:
df['City'] = df['City'].replace({
    'NY': 'New York',
    'Nwe Yrok': 'New York',
    'newyork': 'New York',
    'la': 'Los Angeles',
    'chicago': 'Chicago'
})

In [49]:
df['City'].value_counts()

City
New York       4014
Chicago        2019
Los Angeles    1941
Boston         1023
Unknown        1003
Name: count, dtype: int64

In [50]:
df['Medications'] = df['Medications'].replace({
    'aspirin,metformin': 'Aspirin; Metformin',
    'Aspirin; Metformin': 'Aspirin; Metformin',
    'Lisinopril / Metformin': 'Lisinopril; Metformin'
})

In [51]:
df['Follow_Up'] = df['Follow_Up'].replace({
    'two weeks': '14'
})

df['Follow_Up'] = pd.to_numeric(df['Follow_Up'], errors='coerce')

In [52]:
df['Follow_Up'] = df['Follow_Up'].fillna(df['Follow_Up'].median())

In [53]:
df['Diagnosis_Code'] = df['Diagnosis_Code'].replace({
    'unknown': 'Unknown'
})

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                10000 non-null  float64
 1   Gender             10000 non-null  str
 2   City               10000 non-null  str
 3   BMI                10000 non-null  float64
 4   Blood_Pressure     7970 non-null   str
 5   Heart_Rate         10000 non-null  float64
 6   Cholesterol_Level  10000 non-null  float64
 7   Diabetic           10000 non-null  str
 8   Smoker             10000 non-null  str
 9   Medications        10000 non-null  str
 10  Follow_Up          10000 non-null  float64
 11  Diagnosis_Code     10000 non-null  str
 12  Has_Disease        10000 non-null  str
 13  Systolic_BP        10000 non-null  float64
 14  Diastolic_BP       10000 non-null  float64
dtypes: float64(7), str(8)
memory usage: 1.1 MB

In [56]:
df.shape

(10000, 15)

In [57]:
for col in ['City', 'Medications', 'Follow_Up', 'Diagnosis_Code', 'Has_Disease']:
    print("\n", col)
    print(df[col].value_counts())

 City
City
New York       4014
Chicago        2019
Los Angeles    1941
Boston         1023
Unknown        1003
Name: count, dtype: int64

 Medications
Medications
Unknown                  4024
Aspirin; Metformin       3965
Lisinopril; Metformin    2011
Name: count, dtype: int64

 Follow_Up
Follow_Up
14.0    7526
30.0    2474
Name: count, dtype: int64

 Diagnosis_Code
Diagnosis_Code
Unknown    3366
B20        1700
I10        1664
E11.9      1663
A00        1607
Name: count, dtype: int64

 Has_Disease
Has_Disease
Unknown    2520
0          2513
unknown    2506
1          2461
Name: count, dtype: int64

In [58]:
df['Has_Disease'] = df['Has_Disease'].replace({
    'unknown': 'Unknown'
})

In [59]:
df['Has_Disease'].value_counts()

Has_Disease
Unknown    5026
0          2513
1          2461
Name: count, dtype: int64

In [60]:
numeric_cols = [
    'Age',
    'BMI',
    'Heart_Rate',
    'Cholesterol_Level',
    'Systolic_BP',
    'Diastolic_BP',
    'Follow_Up'
]

df[numeric_cols].describe()

,Age,BMI,Heart_Rate,Cholesterol_Level,Systolic_BP,Diastolic_BP,Follow_Up
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,83.83780,23.109350,169.108200,201.820000,120.913500,79.992700,17.958400
std,97.55259,3.057997,195.258957,23.865133,9.326302,5.289862,6.904364
min,-5.00000,15.000000,0.000000,190.000000,90.000000,60.000000,14.000000
25%,-5.00000,22.500000,51.000000,190.000000,120.000000,80.000000,14.000000
50%,48.00000,22.500000,87.000000,190.000000,120.000000,80.000000,14.000000
75%,97.00000,22.500000,500.000000,190.000000,120.000000,80.000000,14.000000
max,250.00000,35.000000,500.000000,250.000000,160.000000,100.000000,30.000000

In [61]:
df.loc[(df['Age'] < 0) | (df['Age'] > 100), 'Age'] = pd.NA

df['Age'] = df['Age'].fillna(df['Age'].median())

In [62]:
df['Heart_Rate'].value_counts().head(15)

Heart_Rate
500.0    2515
87.0     2499
0.0      2452
85.0       50
109.0      50
79.0       49
107.0      49
63.0       48
120.0      47
106.0      45
89.0       45
119.0      45
105.0      44
76.0       43
104.0      43
Name: count, dtype: int64

In [63]:
# Replace invalid heart rates with missing values
df.loc[
    (df['Heart_Rate'] <= 0) | (df['Heart_Rate'] > 250),
    'Heart_Rate'
] = pd.NA

# Fill missing heart rates with the median
df['Heart_Rate'] = df['Heart_Rate'].fillna(df['Heart_Rate'].median())

In [64]:
df['Heart_Rate'].describe()

count    10000.000000
mean        86.571100
std         10.478966
min         50.000000
25%         87.000000
50%         87.000000
75%         87.000000
max        120.000000
Name: Heart_Rate, dtype: float64

In [65]:
df['Cholesterol_Level'].value_counts().head(15)

Cholesterol_Level
190.0    8030
250.0    1970
Name: count, dtype: int64

In [66]:
df['Age'].describe()

count    10000.000000
mean        48.420100
std         14.717958
min          0.000000
25%         48.000000
50%         48.000000
75%         48.000000
max        100.000000
Name: Age, dtype: float64

In [67]:
df.loc[(df['Age'] <= 0) | (df['Age'] > 100), 'Age'] = pd.NA
df['Age'] = df['Age'].fillna(df['Age'].median())

In [68]:
df['Age'].describe()

count    10000.000000
mean        48.511300
std         14.565551
min          1.000000
25%         48.000000
50%         48.000000
75%         48.000000
max        100.000000
Name: Age, dtype: float64

In [69]:
df['Age'].value_counts().sort_index().head(15)

Age
1.0     22
2.0     19
3.0     27
4.0     15
5.0     33
6.0     37
7.0     20
8.0     27
9.0     20
10.0    33
11.0    34
12.0    24
13.0    29
14.0    27
15.0    30
Name: count, dtype: int64

In [70]:
df.loc[df['Age'] < 18, 'Age'] = pd.NA
df['Age'] = df['Age'].fillna(df['Age'].median())

In [71]:
df['Age'].value_counts().sort_index().head(15)

Age
18.0    26
19.0    37
20.0    23
21.0    33
22.0    25
23.0    28
24.0    25
25.0    24
26.0    25
27.0    22
28.0    27
29.0    19
30.0    19
31.0    33
32.0    23
Name: count, dtype: int64

In [72]:
df.isnull().sum()

Age                     0
Gender                  0
City                    0
BMI                     0
Blood_Pressure       2030
Heart_Rate              0
Cholesterol_Level       0
Diabetic                0
Smoker                  0
Medications             0
Follow_Up               0
Diagnosis_Code          0
Has_Disease             0
Systolic_BP             0
Diastolic_BP            0
dtype: int64

In [73]:
df.drop(columns=['Blood_Pressure'], inplace=True)

In [74]:
df.isnull().sum()

Age                  0
Gender               0
City                 0
BMI                  0
Heart_Rate           0
Cholesterol_Level    0
Diabetic             0
Smoker               0
Medications          0
Follow_Up            0
Diagnosis_Code       0
Has_Disease          0
Systolic_BP          0
Diastolic_BP         0
dtype: int64

In [75]:
df.duplicated().sum()

np.int64(506)

In [76]:
df = df.drop_duplicates()

In [77]:
df.shape

(9494, 14)

In [78]:
df.duplicated().sum()

np.int64(0)

In [79]:
df.info

<bound method DataFrame.info of        Age   Gender         City   BMI  Heart_Rate  Cholesterol_Level  \
0     48.0  Unknown       Boston  22.5        83.0              190.0
1     48.0   Female     New York  25.8        87.0              190.0
2     48.0  Unknown     New York  22.5        87.0              190.0
3     80.0   Female     New York  33.4        87.0              250.0
4     48.0     Male  Los Angeles  30.1        87.0              190.0
...    ...      ...          ...   ...         ...                ...
9995  48.0   Female  Los Angeles  22.5        87.0              190.0
9996  48.0   Female  Los Angeles  22.5        87.0              190.0
9997  48.0  Unknown     New York  22.5        71.0              190.0
9998  48.0  Unknown      Chicago  22.4        87.0              190.0
9999  48.0  Unknown      Chicago  22.5        87.0              190.0

     Diabetic  Smoker            Medications  Follow_Up Diagnosis_Code  \
0     Unknown     Yes                Unknown       30.0            A00
1          No      No                Unknown       14.0        Unknown
2          No  Former     Aspirin; Metformin       30.0            B20
3         Yes  Former                Unknown       30.0        Unknown
4          No      No                Unknown       14.0            I10
...       ...     ...                    ...        ...            ...
9995       No  Former     Aspirin; Metformin       14.0          E11.9
9996      Yes  Former     Aspirin; Metformin       14.0            I10
9997  Unknown  Former  Lisinopril; Metformin       14.0            B20
9998      Yes  Former                Unknown       14.0            B20
9999      Yes  Former                Unknown       14.0          E11.9

     Has_Disease  Systolic_BP  Diastolic_BP
0              0        120.0          80.0
1        Unknown        120.0          80.0
2        Unknown        120.0          80.0
3        Unknown        120.0          80.0
4              1        120.0          80.0
...          ...          ...           ...
9995           0        120.0          80.0
9996     Unknown        120.0          80.0
9997           0        120.0          80.0
9998           0        112.0          98.0
9999     Unknown        120.0          80.0

[9494 rows x 14 columns]>

In [80]:
df['Has_Disease'] = df['Has_Disease'].replace({
    'unknown': 'Unknown'
})

In [81]:
df['Gender'] = df['Gender'].replace({
    'Male': 1,
    'Female': 0,
    'Unknown': 0
})

df['Diabetic'] = df['Diabetic'].replace({
    'Yes': 1,
    'No': 0,
    'Unknown': 0
})

df['Smoker'] = df['Smoker'].replace({
    'Yes': 1,
    'No': 0,
    'Former': 1,
    'Unknown': 0
})

In [82]:
df_ml = df[df['Has_Disease'] != 'Unknown'].copy()

df_ml['Has_Disease'] = pd.to_numeric(
    df_ml['Has_Disease'],
    errors='raise'
).astype(int)

In [83]:
df_ml = pd.get_dummies(
    df_ml,
    columns=['City', 'Medications', 'Diagnosis_Code'],
    dtype=int
)

In [84]:
df_ml.info()

<class 'pandas.DataFrame'>
Index: 4810 entries, 0 to 9998
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                4810 non-null   float64
 1   Gender                             4810 non-null   object
 2   BMI                                4810 non-null   float64
 3   Heart_Rate                         4810 non-null   float64
 4   Cholesterol_Level                  4810 non-null   float64
 5   Diabetic                           4810 non-null   object
 6   Smoker                             4810 non-null   object
 7   Follow_Up                          4810 non-null   float64
 8   Has_Disease                        4810 non-null   int64
 9   Systolic_BP                        4810 non-null   float64
 10  Diastolic_BP                       4810 non-null   float64
 11  City_Boston                        4810 non-null   int64
 12  City_Chicago                       4810 non-null   int64
 13  City_Los Angeles                   4810 non-null   int64
 14  City_New York                      4810 non-null   int64
 15  City_Unknown                       4810 non-null   int64
 16  Medications_Aspirin; Metformin     4810 non-null   int64
 17  Medications_Lisinopril; Metformin  4810 non-null   int64
 18  Medications_Unknown                4810 non-null   int64
 19  Diagnosis_Code_A00                 4810 non-null   int64
 20  Diagnosis_Code_B20                 4810 non-null   int64
 21  Diagnosis_Code_E11.9               4810 non-null   int64
 22  Diagnosis_Code_I10                 4810 non-null   int64
 23  Diagnosis_Code_Unknown             4810 non-null   int64
dtypes: float64(7), int64(14), object(3)
memory usage: 939.5+ KB

In [85]:
df.to_csv("Patient_Health_Records_Cleaned.csv", index=False)

In [86]:
import os

os.path.exists("Patient_Health_Records_Cleaned.csv")

True

In [87]:
df.to_csv(
    "/mnt/c/Users/manav/OneDrive/Desktop/paitent health/Patient_Health_Records_Cleaned.csv",
    index=False
)

In [88]:
df_ml['Gender'] = df_ml['Gender'].replace({
    'Male': 1,
    'Female': 0,
    'Unknown': 0
})

df_ml['Diabetic'] = df_ml['Diabetic'].replace({
    'Yes': 1,
    'No': 0,
    'Unknown': 0
})

df_ml['Smoker'] = df_ml['Smoker'].replace({
    'Yes': 1,
    'No': 0,
    'Former': 1,
    'Unknown': 0
})

In [89]:
df_ml.info()

<class 'pandas.DataFrame'>
Index: 4810 entries, 0 to 9998
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                4810 non-null   float64
 1   Gender                             4810 non-null   object
 2   BMI                                4810 non-null   float64
 3   Heart_Rate                         4810 non-null   float64
 4   Cholesterol_Level                  4810 non-null   float64
 5   Diabetic                           4810 non-null   object
 6   Smoker                             4810 non-null   object
 7   Follow_Up                          4810 non-null   float64
 8   Has_Disease                        4810 non-null   int64
 9   Systolic_BP                        4810 non-null   float64
 10  Diastolic_BP                       4810 non-null   float64
 11  City_Boston                        4810 non-null   int64
 12  City_Chicago                       4810 non-null   int64
 13  City_Los Angeles                   4810 non-null   int64
 14  City_New York                      4810 non-null   int64
 15  City_Unknown                       4810 non-null   int64
 16  Medications_Aspirin; Metformin     4810 non-null   int64
 17  Medications_Lisinopril; Metformin  4810 non-null   int64
 18  Medications_Unknown                4810 non-null   int64
 19  Diagnosis_Code_A00                 4810 non-null   int64
 20  Diagnosis_Code_B20                 4810 non-null   int64
 21  Diagnosis_Code_E11.9               4810 non-null   int64
 22  Diagnosis_Code_I10                 4810 non-null   int64
 23  Diagnosis_Code_Unknown             4810 non-null   int64
dtypes: float64(7), int64(14), object(3)
memory usage: 939.5+ KB

In [90]:
print(df_ml['Gender'].value_counts())
print(df_ml['Diabetic'].value_counts())
print(df_ml['Smoker'].value_counts())

Gender
0    3232
1    1578
Name: count, dtype: int64
Diabetic
0    3241
1    1569
Name: count, dtype: int64
Smoker
1    2450
0    2360
Name: count, dtype: int64

In [91]:
df_ml['Gender'] = df_ml['Gender'].map({
    'Male': 1,
    'Female': 0,
    'Unknown': 0
})

df_ml['Diabetic'] = df_ml['Diabetic'].map({
    'Yes': 1,
    'No': 0,
    'Unknown': 0
})

df_ml['Smoker'] = df_ml['Smoker'].map({
    'Yes': 1,
    'No': 0,
    'Former': 1,
    'Unknown': 0
})

In [92]:
df_ml.info()

<class 'pandas.DataFrame'>
Index: 4810 entries, 0 to 9998
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                4810 non-null   float64
 1   Gender                             0 non-null      float64
 2   BMI                                4810 non-null   float64
 3   Heart_Rate                         4810 non-null   float64
 4   Cholesterol_Level                  4810 non-null   float64
 5   Diabetic                           0 non-null      float64
 6   Smoker                             0 non-null      float64
 7   Follow_Up                          4810 non-null   float64
 8   Has_Disease                        4810 non-null   int64
 9   Systolic_BP                        4810 non-null   float64
 10  Diastolic_BP                       4810 non-null   float64
 11  City_Boston                        4810 non-null   int64
 12  City_Chicago                       4810 non-null   int64
 13  City_Los Angeles                   4810 non-null   int64
 14  City_New York                      4810 non-null   int64
 15  City_Unknown                       4810 non-null   int64
 16  Medications_Aspirin; Metformin     4810 non-null   int64
 17  Medications_Lisinopril; Metformin  4810 non-null   int64
 18  Medications_Unknown                4810 non-null   int64
 19  Diagnosis_Code_A00                 4810 non-null   int64
 20  Diagnosis_Code_B20                 4810 non-null   int64
 21  Diagnosis_Code_E11.9               4810 non-null   int64
 22  Diagnosis_Code_I10                 4810 non-null   int64
 23  Diagnosis_Code_Unknown             4810 non-null   int64
dtypes: float64(10), int64(14)
memory usage: 939.5 KB

In [93]:
print("Gender:")
print(df_ml['Gender'].value_counts(dropna=False))

print("\nDiabetic:")
print(df_ml['Diabetic'].value_counts(dropna=False))

print("\nSmoker:")
print(df_ml['Smoker'].value_counts(dropna=False))

Gender:
Gender
NaN    4810
Name: count, dtype: int64

Diabetic:
Diabetic
NaN    4810
Name: count, dtype: int64

Smoker:
Smoker
NaN    4810
Name: count, dtype: int64

In [94]:
df_ml = df[df['Has_Disease'] != 'Unknown'].copy()

In [95]:
df_ml.info()

<class 'pandas.DataFrame'>
Index: 4810 entries, 0 to 9998
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                4810 non-null   float64
 1   Gender             4810 non-null   object
 2   City               4810 non-null   str
 3   BMI                4810 non-null   float64
 4   Heart_Rate         4810 non-null   float64
 5   Cholesterol_Level  4810 non-null   float64
 6   Diabetic           4810 non-null   object
 7   Smoker             4810 non-null   object
 8   Medications        4810 non-null   str
 9   Follow_Up          4810 non-null   float64
 10  Diagnosis_Code     4810 non-null   str
 11  Has_Disease        4810 non-null   str
 12  Systolic_BP        4810 non-null   float64
 13  Diastolic_BP       4810 non-null   float64
dtypes: float64(7), object(3), str(4)
memory usage: 563.7+ KB

In [96]:
print("Gender:")
print(df_ml['Gender'].value_counts())

print("\nDiabetic:")
print(df_ml['Diabetic'].value_counts())

print("\nSmoker:")
print(df_ml['Smoker'].value_counts())

Gender:
Gender
0    3232
1    1578
Name: count, dtype: int64

Diabetic:
Diabetic
0    3241
1    1569
Name: count, dtype: int64

Smoker:
Smoker
1    2450
0    2360
Name: count, dtype: int64

In [97]:
df_ml.info()

<class 'pandas.DataFrame'>
Index: 4810 entries, 0 to 9998
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                4810 non-null   float64
 1   Gender             4810 non-null   object
 2   City               4810 non-null   str
 3   BMI                4810 non-null   float64
 4   Heart_Rate         4810 non-null   float64
 5   Cholesterol_Level  4810 non-null   float64
 6   Diabetic           4810 non-null   object
 7   Smoker             4810 non-null   object
 8   Medications        4810 non-null   str
 9   Follow_Up          4810 non-null   float64
 10  Diagnosis_Code     4810 non-null   str
 11  Has_Disease        4810 non-null   str
 12  Systolic_BP        4810 non-null   float64
 13  Diastolic_BP       4810 non-null   float64
dtypes: float64(7), object(3), str(4)
memory usage: 563.7+ KB

In [98]:
df_ml.head()

,Age,Gender,City,BMI,Heart_Rate,Cholesterol_Level,Diabetic,Smoker,Medications,Follow_Up,Diagnosis_Code,Has_Disease,Systolic_BP,Diastolic_BP
0,48.0,0,Boston,22.5,83.0,190.0,0,1,Unknown,30.0,A00,0,120.0,80.0
4,48.0,1,Los Angeles,30.1,87.0,190.0,0,0,Unknown,14.0,I10,1,120.0,80.0
5,48.0,0,Unknown,22.5,63.0,190.0,0,1,Unknown,30.0,E11.9,0,120.0,80.0
8,48.0,0,Boston,22.5,87.0,190.0,0,1,Aspirin; Metformin,30.0,Unknown,0,120.0,80.0
9,48.0,0,Chicago,21.5,87.0,190.0,0,1,Unknown,30.0,A00,1,120.0,80.0

In [99]:
# 1. Create ML dataset
df_ml = df[df['Has_Disease'] != 'Unknown'].copy()

# 2. Convert binary columns to 0/1
df_ml['Gender'] = df_ml['Gender'].map({
    'Male': 1,
    'Female': 0,
    'Unknown': 0
})

df_ml['Diabetic'] = df_ml['Diabetic'].map({
    'Yes': 1,
    'No': 0,
    'Unknown': 0
})

df_ml['Smoker'] = df_ml['Smoker'].map({
    'Yes': 1,
    'No': 0,
    'Former': 1,
    'Unknown': 0
})

# 3. Convert target to 0/1
df_ml['Has_Disease'] = pd.to_numeric(df_ml['Has_Disease']).astype(int)

# 4. One-hot encode multi-category columns
df_ml = pd.get_dummies(
    df_ml,
    columns=['City', 'Medications', 'Diagnosis_Code'],
    dtype=int
)

# 5. Check result
df_ml.info()

<class 'pandas.DataFrame'>
Index: 4810 entries, 0 to 9998
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                4810 non-null   float64
 1   Gender                             0 non-null      float64
 2   BMI                                4810 non-null   float64
 3   Heart_Rate                         4810 non-null   float64
 4   Cholesterol_Level                  4810 non-null   float64
 5   Diabetic                           0 non-null      float64
 6   Smoker                             0 non-null      float64
 7   Follow_Up                          4810 non-null   float64
 8   Has_Disease                        4810 non-null   int64
 9   Systolic_BP                        4810 non-null   float64
 10  Diastolic_BP                       4810 non-null   float64
 11  City_Boston                        4810 non-null   int64
 12  City_Chicago                       4810 non-null   int64
 13  City_Los Angeles                   4810 non-null   int64
 14  City_New York                      4810 non-null   int64
 15  City_Unknown                       4810 non-null   int64
 16  Medications_Aspirin; Metformin     4810 non-null   int64
 17  Medications_Lisinopril; Metformin  4810 non-null   int64
 18  Medications_Unknown                4810 non-null   int64
 19  Diagnosis_Code_A00                 4810 non-null   int64
 20  Diagnosis_Code_B20                 4810 non-null   int64
 21  Diagnosis_Code_E11.9               4810 non-null   int64
 22  Diagnosis_Code_I10                 4810 non-null   int64
 23  Diagnosis_Code_Unknown             4810 non-null   int64
dtypes: float64(10), int64(14)
memory usage: 939.5 KB

In [101]:
# Start again from the original cleaned dataframe
df_ml = df[df['Has_Disease'] != 'Unknown'].copy()

# Convert binary columns
df_ml['Gender'] = df_ml['Gender'].replace({
    'Male': 1,
    'Female': 0,
    'Unknown': 0
})

df_ml['Diabetic'] = df_ml['Diabetic'].replace({
    'Yes': 1,
    'No': 0,
    'Unknown': 0
})

df_ml['Smoker'] = df_ml['Smoker'].replace({
    'Yes': 1,
    'No': 0,
    'Former': 1,
    'Unknown': 0
})

# Convert target
df_ml['Has_Disease'] = pd.to_numeric(
    df_ml['Has_Disease'],
    errors='raise'
).astype(int)

# One-hot encode the multi-category columns
df_ml = pd.get_dummies(
    df_ml,
    columns=['City', 'Medications', 'Diagnosis_Code'],
    dtype=int
)

# Check
df_ml.info()

<class 'pandas.DataFrame'>
Index: 4810 entries, 0 to 9998
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                4810 non-null   float64
 1   Gender                             4810 non-null   object
 2   BMI                                4810 non-null   float64
 3   Heart_Rate                         4810 non-null   float64
 4   Cholesterol_Level                  4810 non-null   float64
 5   Diabetic                           4810 non-null   object
 6   Smoker                             4810 non-null   object
 7   Follow_Up                          4810 non-null   float64
 8   Has_Disease                        4810 non-null   int64
 9   Systolic_BP                        4810 non-null   float64
 10  Diastolic_BP                       4810 non-null   float64
 11  City_Boston                        4810 non-null   int64
 12  City_Chicago                       4810 non-null   int64
 13  City_Los Angeles                   4810 non-null   int64
 14  City_New York                      4810 non-null   int64
 15  City_Unknown                       4810 non-null   int64
 16  Medications_Aspirin; Metformin     4810 non-null   int64
 17  Medications_Lisinopril; Metformin  4810 non-null   int64
 18  Medications_Unknown                4810 non-null   int64
 19  Diagnosis_Code_A00                 4810 non-null   int64
 20  Diagnosis_Code_B20                 4810 non-null   int64
 21  Diagnosis_Code_E11.9               4810 non-null   int64
 22  Diagnosis_Code_I10                 4810 non-null   int64
 23  Diagnosis_Code_Unknown             4810 non-null   int64
dtypes: float64(7), int64(14), object(3)
memory usage: 939.5+ KB

In [102]:
print(df_ml['Gender'].unique())
print(df_ml['Diabetic'].unique())
print(df_ml['Smoker'].unique())

[0 1]
[0 1]
[1 0]

In [103]:
df_ml.isnull().sum()

Age                                  0
Gender                               0
BMI                                  0
Heart_Rate                           0
Cholesterol_Level                    0
Diabetic                             0
Smoker                               0
Follow_Up                            0
Has_Disease                          0
Systolic_BP                          0
Diastolic_BP                         0
City_Boston                          0
City_Chicago                         0
City_Los Angeles                     0
City_New York                        0
City_Unknown                         0
Medications_Aspirin; Metformin       0
Medications_Lisinopril; Metformin    0
Medications_Unknown                  0
Diagnosis_Code_A00                   0
Diagnosis_Code_B20                   0
Diagnosis_Code_E11.9                 0
Diagnosis_Code_I10                   0
Diagnosis_Code_Unknown               0
dtype: int64

In [104]:
df_ml.info()

<class 'pandas.DataFrame'>
Index: 4810 entries, 0 to 9998
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                4810 non-null   float64
 1   Gender                             4810 non-null   object
 2   BMI                                4810 non-null   float64
 3   Heart_Rate                         4810 non-null   float64
 4   Cholesterol_Level                  4810 non-null   float64
 5   Diabetic                           4810 non-null   object
 6   Smoker                             4810 non-null   object
 7   Follow_Up                          4810 non-null   float64
 8   Has_Disease                        4810 non-null   int64
 9   Systolic_BP                        4810 non-null   float64
 10  Diastolic_BP                       4810 non-null   float64
 11  City_Boston                        4810 non-null   int64
 12  City_Chicago                       4810 non-null   int64
 13  City_Los Angeles                   4810 non-null   int64
 14  City_New York                      4810 non-null   int64
 15  City_Unknown                       4810 non-null   int64
 16  Medications_Aspirin; Metformin     4810 non-null   int64
 17  Medications_Lisinopril; Metformin  4810 non-null   int64
 18  Medications_Unknown                4810 non-null   int64
 19  Diagnosis_Code_A00                 4810 non-null   int64
 20  Diagnosis_Code_B20                 4810 non-null   int64
 21  Diagnosis_Code_E11.9               4810 non-null   int64
 22  Diagnosis_Code_I10                 4810 non-null   int64
 23  Diagnosis_Code_Unknown             4810 non-null   int64
dtypes: float64(7), int64(14), object(3)
memory usage: 939.5+ KB

In [105]:
df_ml['Gender'] = pd.to_numeric(df_ml['Gender']).astype(int)
df_ml['Diabetic'] = pd.to_numeric(df_ml['Diabetic']).astype(int)
df_ml['Smoker'] = pd.to_numeric(df_ml['Smoker']).astype(int)

In [106]:
df_ml.info()

<class 'pandas.DataFrame'>
Index: 4810 entries, 0 to 9998
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                4810 non-null   float64
 1   Gender                             4810 non-null   int64
 2   BMI                                4810 non-null   float64
 3   Heart_Rate                         4810 non-null   float64
 4   Cholesterol_Level                  4810 non-null   float64
 5   Diabetic                           4810 non-null   int64
 6   Smoker                             4810 non-null   int64
 7   Follow_Up                          4810 non-null   float64
 8   Has_Disease                        4810 non-null   int64
 9   Systolic_BP                        4810 non-null   float64
 10  Diastolic_BP                       4810 non-null   float64
 11  City_Boston                        4810 non-null   int64
 12  City_Chicago                       4810 non-null   int64
 13  City_Los Angeles                   4810 non-null   int64
 14  City_New York                      4810 non-null   int64
 15  City_Unknown                       4810 non-null   int64
 16  Medications_Aspirin; Metformin     4810 non-null   int64
 17  Medications_Lisinopril; Metformin  4810 non-null   int64
 18  Medications_Unknown                4810 non-null   int64
 19  Diagnosis_Code_A00                 4810 non-null   int64
 20  Diagnosis_Code_B20                 4810 non-null   int64
 21  Diagnosis_Code_E11.9               4810 non-null   int64
 22  Diagnosis_Code_I10                 4810 non-null   int64
 23  Diagnosis_Code_Unknown             4810 non-null   int64
dtypes: float64(7), int64(17)
memory usage: 939.5 KB

In [107]:
df_ml.isnull().sum().sum()

np.int64(0)

In [108]:
X = df_ml.drop('Has_Disease', axis=1)
y = df_ml['Has_Disease']

In [109]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (4810, 23)
y shape: (4810,)

In [110]:
print(y.value_counts())

Has_Disease
0    2424
1    2386
Name: count, dtype: int64